### ISSUE TITLE
can't open test files

### ISSUE THREAD

**Issue by NaimaSadeghi** [agviegas/test-ifc-files#1]
Hello,
I used your ifcjs-hello-world-main and tried to open one of your sample ifc files with it. However, nothing is changed in my browser when opening sample files.

**Comment by agviegas** [comment]
Hi! What file did you try to open? Can you check if you have the same problem [in the deployed version](https://agviegas.github.io/ifcjs-hello-world/)?

**Comment by NaimaSadeghi** [comment]
Thanks for your reply. I tried "rst_advanced_sample_project.ifc". There is no problem wih the deployed version.  What I did is that I downloaded the project on my computer and opened the index file. I was not able to open any IFC file in this way. Am I doing something wrong?

**Comment by agviegas** [comment]
You can't open an HTML file directly in the browser, you need a local server. Did you check the [documentation](https://agviegas.github.io/ifcjs-docs/#/)?

**Comment by NaimaSadeghi** [comment]
I'll check it out, thank you.
